Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raspberry/RPC-client-server/RPCClient_1.py", line 188, in ArmPi_client
    ArmPi_catch(Armclient,DBClient,num)#机械臂组组号 0 1
  File "/home/raspberry/RPC-client-server/RPCClient_1.py", line 209, in ArmPi_catch
    if not ArmPi_free(Armclient):
  File "/home/raspberry/RPC-client-server/RPCClient_1.py", line 139, in ArmPi_free
    if state[2]==0 :
IndexError: list index out of range
[INFO] start detec IsFree
[False, 'E04 - Operation timeout!']
[False, 'E04 - Operation timeout!']
Is Free True
[INFO] start detec ArmPi_free()
state [True, 0]
